spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csteach?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
  devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        exclude: WEB-INF/**

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  sms:
    accessKeyId: 11 #创建的accesskey中的AccessKey ID
    accessKeySecret: 11 #创建的accesskey中的Access Key Secret
    template_code: 111 #模板管理中的模板CODE
    sign_name: 111  #签名管理中的签名

server:
  port: 9092

